### ISSUE TITLE
Compile MOM6 on Cheyenne

### ISSUE THREAD

**Issue by yueyanglu** [NCAR/MOM6-cases#21]
Hello,

I was compiling MOM6 on Cheyenne but got the following error message when building the FMS (libfms.a):

ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/mpp/mpp_parameter.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/platform/platform.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/drifters/drifters_input.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/drifters/cloud_interpolator.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/drifters/drifters_io.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c	../../../../src/FMS/random_numbers/MersenneTwister.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c -I../../../../src/FMS/include	../../../../src/FMS/sat_vapor_pres/sat_vapor_pres_k.F90
ifort -Duse_libMPI -Duse_netCDF -DSPMD -Duse_LARGEFILE  -fpp -Wp,-w -fno-alias -auto -safe-cray-ptr -ftz -assume byterecl -i4 -r8 -nowarn -sox -traceback -O2 -debug minimal -fp-model source -override-limits   -c	../../../../src/FMS/test_fms/drifters/test_quicksort.F90
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:133: recipe for target 'mpp_parameter.o' failed
make: *** [mpp_parameter.o] Error 1
make: *** Waiting for unfinished jobs....
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:65: recipe for target 'drifters_io.o' failed
make: *** [drifters_io.o] Error 1
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:207: recipe for target 'test_quicksort.o' failed
make: *** [test_quicksort.o] Error 1
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:147: recipe for target 'platform.o' failed
make: *** [platform.o] Error 1
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:63: recipe for target 'drifters_input.o' failed
make: *** [drifters_input.o] Error 1
ifort: command line error: option '-override-limits' is not supported. Please use the replacement option '-qoverride-limits'
Makefile:157: recipe for target 'sat_vapor_pres_k.o' failed
make: *** [sat_vapor_pres_k.o] Error 1
Makefile:27: recipe for target 'cloud_interpolator.o' failed
make: *** [cloud_interpolator.o] Error 1
Makefile:13: recipe for target 'MersenneTwister.o' failed
make: *** [MersenneTwister.o] Error 1

My loaded modules are:
    1) ncarenv/1.3     2) intel/19.0.5    3) netcdf/4.7.4      4) ncarcompilers/0.5.0     5) mpt/2.22
    
The command that I used to build FMS (the makefile for FMS was generated successfully) but got the above error was:
`make NETCDF=3 REPRO=1 libfms.a -j`

I checked that the file "cheyenne-intel.mk" was in the directory "~/MOM6-cases/src/mkmf/templates/". 

Thank you!
Yueyang

**Comment by gustavo-marques** [comment]
We have not updated MOM6-cases in a while. Please try updating FMS to [FMS @ f61416f](https://github.com/NOAA-GFDL/FMS/tree/f61416fef691d9ba39a40df1ce72aa574f54c390) and MOM6 to [MOM6 @ dev/ncar](https://github.com/NCAR/MOM6)

**Comment by yueyanglu** [comment]
> We have not updated MOM6-cases in a while. Please try updating FMS to [FMS @ f61416f](https://github.com/NOAA-GFDL/FMS/tree/f61416fef691d9ba39a40df1ce72aa574f54c390) and MOM6 to [MOM6 @ dev/ncar](https://github.com/NCAR/MOM6)

Thank you for the reply. This compiling issue has been resolved.
